---
#title: "Macroenometrics (44343)"
output:
  html_document:
    #css: !expr here::here("assets", "styles_pjp.css") 
    css: assets/styles_pjp.css
    theme: united
    highlight: monochrome 
    self_contained: yes
    number_sections: no
    toc: true
    toc_float: true
---


```{r, echo = FALSE}
library(metathis)
meta() %>% meta_description(
    "Curso de introduccion a R"
  ) %>% 
  meta_name("github-repo" = "perezp44/intro-ds-20-21-web") %>% 
  meta_viewport() %>% 
  meta_social(
    title = "Curso de introducción a R",
    url = "https://perezp44.github.io/intro-ds-20-21-web/",
    og_type = "course",
    og_author = c("Pedro J. Pérez"))
```

<!-- This comment will not de displayed in any format-->

<br>

-------------------

En esta sección voy a contaros un poco la filosofía/enfoque del curso; principalmente cómo será la forma de trabajar en clase y en casa^[Tenéis también que tener claro que lo que voy a escribir aquí puede estar sujeto a cambios, ¿qué porqué pueden haber cambios? pues por muchas razones, una de ellas es evolución de la pandemia, otra es que aún no os conozco.]. También diré algo sobre la evaluación. 

<br>

## Introducción

------------------

#### Resumen

Como posiblemente sepáis, y si no ya os lo contaré yo el primer día de clase, el curso es una introducción a la ciencia de datos con R; de hecho el título del curso debería ser: `Introducción a la Ciencia de datos`; o de forma más precisa y extensa: "Una introducción a la Ciencia de datos con R para economistas". 

#### Relación de temas

El curso tiene **"sólo" 5 temas**. En el primer tema se presentan los objetivos del curso, junto con los términos y procesos que justifican la asignatura (Big data, Ciencia de Datos, Machine Learning, investigación reproducible...). En el tema 2 se presentan los rudimentos del lenguaje de programación R. Estos conocimientos básicos se irán reforzando durante el curso trabajando en diferentes tópicos y aplicaciones. En el tema 3, se desarrollarán diversos casos de análisis de datos tabulares, el formato más típico en Ciencias Sociales, con los que se irán asentando los conocimientos de programación iniciados en el tema 2. El tema 4 es una introducción a los conceptos básicos del Machine Learning (training set, validation set, etc..), para luego presentar las técnicas o algoritmos de ML básicos y más relacionados con lo que los estudiantes ya han visto en Econometría, ahora presentados desde una óptica diferente, más orientada a la predicción. El quinto y último tema presenta, una vez habéis alcanzado cierta soltura en el manejo de R, una panorámica de tópicos como, por ejemplo, datos espaciales y textuales.

A pesar de que la guía docente presenta 5 temas, en el curso no trabajaremos estrictamente por temas sino más bien por tópicos: iremos presentando tópicos/ideas/funciones conforme nos vayan haciendo falta para resolver alguna tarea/problema. En esta asignatura creo que es mejor avanzar en el contenido del curso de forma no lineal y priorizar el trabajo práctico y aplicado: avanzaremos sin haber visto en detalle algunos tópicos/ideas, pero volveremos más adelante a ellas; de forma que, durante las primeras sesiones te surgirán muchas dudas, es normal!! Algunas de ellas las contestaré, pero en otras diré: ya las contestaremos más adelante!! Poco a poco iremos profundizando y comprendiendo mejor lo que hacemos. Explicaré con más detalle este punto en clase.


----------------

<br>

## Desarrollo de las clases


Como sabéis las clases esta previsto que sean presenciales, así que la dinámica de las clases será parecida a lo que estáis acostumbrados, digo parecida porque hay un protocolo covid que deberemos seguir. Supongo que en unas semanas ya estaremos acostumbrados.

Es necesario acudir con un **ordenador portátil**, mejor si es tu propio ordenador, ya que las clases serán eminentemente prácticas: estaremos buena parte de las sesiones trabajando con el ordenador. 

Nos veremos un día a la semana, los viernes. En esta misma web, en la sección [`Calendario`](https://perezp44.github.io/intro-ds-20-21-web/03-calendario.html) detallaré qué haremos en cada sesión, tanto en clase, como antes de venir a clase. Antes de venir a clase tendréis que leer el planning para la próxima sesión y realizar las tareas que tengáis asignadas para ese día. Generalmente, las tareas consistirán en leer algún material, pero algunas veces tendréis que realizar alguna tarea que formará parte de la evaluación continua. 


<div class = "blue">
<br> Repito, **tendréis que hacer unas tareas antes de venir a clase**. Algunas de ellas las recogeré porque forman parte de la evaluación continua. Podrás ver las tareas y el guión de cada clase en la sección [`Calendario`](https://perezp44.github.io/intro-ds-20-21-web/03-calendario.html) de esta misma web.  <br>
</div>

<br>

#### Sesiones

El curso tiene **13 sesiones de 4 horas** (en realidad 3 horas cada sesión). La verdad es que no me gusta que las sesiones sean de 4 horas pero, dadas las actuales circunstancias, es posible que agrupar las clases en un solo día sea, quizás, la mejor opción.

Las razones por las que, en circunstancias normales, prefiero dos clases a la semana son varias. Una de ellas consiste en que durante la clase hay que pensar bastante (estaremos aprendiendo un lenguaje) y hacer ejercicios y pruebas y acabaréis cansados, espero que contentos por haber aprendido, pero cansados. Otra razón consiste en que faltar un solo día puede ser importante para el seguimiento del curso. Por favor, intentad no faltar a las clases y menos aún a las tres primeras. En las primeras clases se explican cosas/ideas/conceptos que, no es que sean complicadas, de hecho, una vez se entienden son muy sencillas, pero que no son fáciles de entender por uno mismo sin ayuda. Insisto: **no faltéis a clase, pero menos aún a las primeras!!** 

<br>

#### Dinámica de las clases


Ya dentro de clase, la dinámica será la siguiente: el profesor, yo, explicaré una idea/tópico, mostraré una aplicación de ella en el ordenador, para después plantearos un reto o cuestión para que trabajéis la idea/concepto y acabéis de entenderlo. Intentaré^[Digo intentaré porque también depende de vosotros.] repetir este esquema de explicación/aplicación de forma rápida; es decir que veamos cuantos más tópicos mejor. 

Buena parte de las sesiones estaréis resolviendo problemas/cuestiones con el ordenador. Lo ideal es trabajar en parejas, se aprende mucho más y más rápido, pero este año, esto va a ser complicado^[Igual esto no es imposible del todo. Veremos si es posible suplir la proximidad física con alguna aplicación de mensajería.]. Lo normal es atascarse de vez en cuando mientras estás resolviendo una tarea, y muchas veces es tu compañero el que te saca del apuro. Yo tampoco voy a poder pasearme por las mesas para ver como lo estáis haciendo, así que esto limitará, en parte, el que yo pueda ayudaros. 

Esta situación provocada por el covid hará que las clases, al menos las primeras, tengan que ser más **pautadas y pausadas**: no cerraremos un tópico/tarea hasta que todos hayáis acabado, esto implica que iremos un poco más lentos y también implica que **no podéis despistaros** ya que si no seguís el ritmo se resentirá el aprendizaje de vuestros compañeros. Buff, que estrés!!! No, yo creo que al final las cosas saldrán bien y nos divertiremos y aprenderemos, **PERO** tenéis que tener muy claro que **no podéis venir a clase de espectadores** a ver que ocurre, tenéis que trabajar en clase y haber trabajado en casa, no os podéis quedar atrás. Si te vas quedando atrás, en una o dos clases no entenderás nada, y no porque las cosas que veamos sean difíciles, no, sino que hay que ir paso a paso y, a veces, entenderlas por tu cuenta sí que es complicado. 


------------------

<br>

## The "plan"

Mi idea/plan es **confiar en que os va a gustar la asignatura** y que vais a trabajar lo necesario, tanto en casa como en clase, con lo que las clases serán fáciles a pesar de las limitaciones impuestas por el covid.

Como os he dicho, las clases son los viernes, antes de cada clase publicaré en esta web, en la sección [`Calendario`](https://perezp44.github.io/intro-ds-20-21-web/03-calendario.html) el trabajo previo que tendréis que hacer. Si puedo publicaré esos guiones no mas tarde de los lunes. 

El plan consiste en que vosotros hacéis el trabajo previo antes de venir a clase, de forma que el viernes podéis seguir sin demasiados problemas las clases. De vez en cuando os tendré que hacer pruebas en el aula que también formarán parte de la evaluación continua. 

Las pruebas saldrán bien, espero, lo que querrá decir que estáis aprendiendo, así que todos estaremos contentos y además cumpliremos las recomendaciones sanitarias asi que no tendremos problemas con el covid. Ojala!!


> Everyone has a plan until they get punched in the mouth --- Mike Tyson

A pesar de que confío en que tengamos suerte y podamos cumplir con "the plan", la verdad es que hay, creo, altas probabilidades de que igual, espero que no, la docencia pase a ser online. Ya veríamos que hacemos en ese caso, cruzad los dedos por si acaso^[Además de llevar mascarillas, lavarse manos y respetar distancia de seguridad, vamos cumplir protocolos covid. A ver si pronto salimos de esta!!].


------------------

<br>

## Logística

El curso es eminentemente práctico, por lo que es necesario que los estudiantes tengan acceso a un ordenador durante las clases. Dada la situación sanitaria actual, las clases se impartirán en el aula 103 (aula de teoría) por lo que se hace **necesario que cada estudiante venga a clase con su propio portátil**.

Durante el curso utilizaremos diversos recursos: transparencias, ejemplos, ejercicios, bibliografía, etc... Puedes encontrar todos los detalles en la sección [`Logística`](https://perezp44.github.io/intro-ds-20-21-web/02-logistica.html) de la página web.


------------------

<br>

## Evaluación

Tal como figura en la adenda covid-19 a la [Guía Docente](./pdfs/Guia-Docente.pdf), el **60% de la nota provendrá de la evaluación continua** y el restante 40% lo aportará el examen final.

Los detalles concretos acerca de la evaluación continua puedes consultarlos en [Aula Virtual`](https://aulavirtual.uv.es/course/view.php?id=9254){target="_blank"} 

Aunque quizás fuese mejor, como han hecho en varios países, dejar la evaluación a un algoritmo. Lo puedes leer [aquí](https://www.enriquedans.com/2020/09/algoritmos-y-educacion-no-tan-rapido.html) y [aquí](https://www.eldiario.es/internacional/boris-johnson-da-marcha-modifica-sistema-usaba-algoritmo-calificar-estudiantes_1_6170221.html). Evidentemente lo de usar un algoritmo es una broma. Me gustaría pero ...


--------------------

<br>

## Protocolo covid-19

Ya he hecho referencia varias veces a que tendremos que seguir, evidentemente, el protocolo de la UV. Cuando yo os de clase, el viernes 18, ya sabréis mejor que yo como actuar; pero por lo que parece deberemos llevar mascarilla, lavado de manos, separación de asientos, entradas y salidas escalonadas, restricciones de uso en las áreas comunes. Intentaremos cumplir al máximo con el protocolo, no queremos salir en la tele ni ir al hospital!!

Además, sed responsables, y si tenéis algún síntoma quedaros en casa por precaución; a pesar de que he insistido varias veces que es importante asistir a clase, más importante es la salud. Si alguien tiene que quedarse en casa por este motivo, que contacte conmigo y veremos como organizamos tutorias para que pueda seguir el curso mientras hace la cuarentena o simplemente está en casa por algún síntoma. 

Si algún día yo tengo algún síntoma o sospecha de que puedo tener covid, me quedaré en casa, os avisaría lo antes posible y las clases pararían a impartirse por la BBC del aula virtual en el horario habitual.

- Espero que no, pero si crees que puedes tener covid,  llama al teléfono habilitado por la Generalitat: **ante cualquier síntoma llama al 900 300 555**.

- Un pdf conInstrucciones covid de la UV para vosotros, los estudiantes: <https://www.uv.es/preven/noticies/covid19/9%20sep%20directrius%20prevencio%20centres%20curs%202020-2021%20v1.2.pdf>. Entre otras cosas os dicen que si alguien está en cuarentena o con problemas por la Covid-19, ha de comunicarlo a covid@uv.es y covideconomia@uv.es. 

- Página web de la UV sobre covid: <https://www.uv.es/uvweb/universidad/es/coronavirus-1286119460428.html>{target="_blank"} 


--------------------

<br><br>


## FAQ's

En esta sección pretendo responder a posibles dudas/preguntas que creo que os pueden pasar por la cabeza antes de iniciar el curso. Yo también tengo dudas sobre cómo será el curso: esta va a ser la segunda vez que se imparte el curso en la UV, pero la primera (y espero que última) que se imparte bajo una situación de pandemia. Seguro que tenéis muchas más dudas, hacédmelas llegar por mail o en clase.

<br>

##### Nunca he programado ¿podré seguir el curso?

Por supuesto. Empezaremos con nivel cero, PERO, lo que si que tengo que deciros es que si tu nivel de conocimientos informáticos y/o de programación no es muy elevado (o nulo) haz el esfuerzo de no perderte las 3 primeras clases y tratar de ir entendiéndolo, para eso están las tutorías, **NO lo dejes para el final**, si no, se te hará bola.

<br>

##### ¿Cual es el objetivo último del curso? ¿Qué voy a aprender?

Ya he dicho que el curso es una introducción a la Ciencia de Datos con R. Vas a aprender muchas cosas (espero), pero principalmente a utilizar R para hacer análisis de datos.

Espero que al final del curso seáis capaces de entender código R, replicar los análisis que se publican en sitios como [R-bloggers](https://www.r-bloggers.com/) y ser capaces de hacer análisis de datos propios con R.

El año pasado le dedicamos poco tiempo al proyecto: sólo aportaba 1,25 puntos de la nota final. No le dedicamos tiempo a pulirlos, pero aún así salieron bastante bien. Aquí tienes una muestra de los proyectos que presentaron los estudiantes el curso pasado:

- `Elecciones 28-A`: las [Slides](https://raw.githack.com/jcotanda/elecciones28A/master/slides.html#1), el [Informe](https://raw.githack.com/jcotanda/elecciones28A/master/report.html) y el [repo](https://github.com/jcotanda/elecciones28A)

- `Proyecto-AGA`: las [Slides](https://raw.githack.com/andreu2398/Project-AGA/master/Presentacio.html){target="_blank"}, el [Informe](https://raw.githack.com/andreu2398/Project-AGA/master/Project-AGA--.Rmd--final.html){target="_blank"} y el [repo](https://github.com/andreu2398/Project-AGA){target="_blank"}

- `La revolución del triple en la NBA`: las [Slides](https://raw.githack.com/7antoniosegovia/proyecto_eco_uv/master/NBA_Proyecto/presentacion.html){target="_blank"}, el [Informe](https://raw.githack.com/7antoniosegovia/proyecto_eco_uv/master/NBA_Proyecto/script_informe.html){target="_blank"} y el [repo](https://github.com/7antoniosegovia/proyecto_eco_uv){target="_blank"}

- `Delitos en Europa`: las [Slides](https://raw.githack.com/teodoromouniertebas/ProyectoTeodoroAdrian/master/Proyecto_final_R/Slides/Presentacio.html){target="_blank"}, el [Informe](https://raw.githack.com/teodoromouniertebas/ProyectoTeodoroAdrian/master/Proyecto_final_R/Proyecto/Proyecto-Final-R.html){target="_blank"} y el [repo](https://github.com/teodoromouniertebas/ProyectoTeodoroAdrian){target="_blank"}

<br>

El resto de trabajos están en el [repo del curso 2019-2020](https://github.com/perezp44/tutoriales_intro_DS). No tendrás fácil verlos porque no les enseñe a desplegar sus proyectos en una web. Fallo mio!!! pero es que a todo no se llega.

<br>

##### ¿Será fácil aprobar?

Sí. Creo que te resultará fácil aprobar; de hecho, el año pasado aprobaron todos los que siguieron el curso: todos eran capaces de importar y arreglar datos, mostrar resultados en tablas y gráficos y presentar informes en Rmarkdown. También es verdad que hubo 4-5 estudiantes que, por diversas razones, decidieron abandonar el curso en la tercera semana y se matricularon en otra optativa. De verdad que creo que os gustará y aprenderéis pero ... has de trabajar, sobre todo al principio. 

Si, por lo que sea crees que la asignatura no es para ti^[Insisto, creo que por muy bajo que sea tu nivel de partida, con un interés razonable aprovecharás sin problemas el curso], lo mejor sería darse de baja: este año creo que en secretaría serán mas estrictos con la fechas de cambio de matricula.

<br>

##### ¿Acabaremos el temario?

No lo sé. Depende de vosotros, de mi y de la evolución de la situación sanitaria. El curso tiene **13 sesiones de 4 horas** (en realidad 3 horas cada sesión), de forma que deberían ser suficientes para impartir el contenido de 5 temas, pero resulta que los temas, dependiendo de la profundidad con la que los veamos, pueden hacerse muy extensos. Además, la situación sanitaria actual va a condicionar el formato y prácticas docentes dentro del aula, seguramente ralentizándolas; así que ya veremos hasta donde llegamos. 

<br>

##### ¿Me servirá lo que aprenda en mi (futuro) trabajo?

Pues no lo sé, depende, pero cada vez es más frecuente que las empresas intenten hacer sus análisis y gestión de datos con R. El año pasado al menos dos estudiantes, que yo sepa,  utilizaron R en las empresas en las que estaban haciendo sus prácticas curriculares y otros dos ahora mismo estarán cursando un máster de Análisis de Datos, así que seguro que ahora están usando R.


<br><br>

<div class="tocify-extend-page" data-unique="tocify-extend-page" style="height: 0;"></div>
