---
#title: "Macroenometrics (44343)"
output:
  html_document:
    css: assets/styles_pjp.css
    theme: united
    highlight: monochrome 
    number_sections: no
    toc: true
    toc_float: true
    includes:
       in_header: google-analytics.html
---

<br>

### Calendario de clase y **HOMEWORK**

-------------------

- Este apartado iré actualizándolo conforme pasen las semanas. Aquí os dejaré las tareas previas a cada clase. **TENÉIS** que hacer las tareas previas.


- Las clases serán los viernes de 15:30 a 19:30 en el aula 103 del aulario Sur. Haremos descansos. Veremos cómo.

- Tenemos 13 sesiones. Intenta faltar lo menos posible y asiste, sí o sí, a las 3-4 primeras sesiones.

- Intentaré ajustar y acertar lo más posible la programación pero ... , como sabéis, en una clase siempre puede haber incidentes/sorpresas.



<div class = "blue">
<br> Repito: Antes de venir a clase **TENÉIS** que hacer las tareas previas asignadas.  <br>
</div>


-----------------------

<br>

## 1ª clase (18-sept)

##### **`Homework`** (para hacer antes de ir a clase) 

- Lee la sección [`Guía del curso`](https://perezp44.github.io/intro-ds-20-21-web/01-guia-del-curso.html) de la página web del curso.
  
- Créate una cuenta en [Github](https://github.com/){target="_blank"}. La usaremos para acceder a varios servicios web.

- Prepara tu ordenador; es decir, instálate R, RStudio y los paquetes. [Aquí](./mas-recursos/Instrucciones_instalacion-a.html){target="_blank"} tienes una guía para la instalación. Si tienes algún problema con la instalación contacta conmigo por email.

- Lee el primer turorial: [`Tutorial 01: Introducción`](./tutoriales/tt_01_introduccion.html){target="_blank"}. Es solo leer, no hay que estudiar nada; además se lee fácil. Se trata simplemente de poner en contexto el curso y hablar un poco de que es esto de la "era del Big Data", la ciencia de datos etc ...

- Si quieres, puedes echarle un vistazo a las 2 primeras transparencias: [aquí](./slides/ss_01_presentacion/ss_01_presentacion-curso.html){target="_blank"} y [aquí](./slides/ss_02_tema-1/ss_02_tema-1.html){target="_blank"}. 


<br>

##### ¿Qué haremos en la primera clase?

  - Lo primero presentar el curso 

  - Hablar de la evaluación y forma de trabajo en el curso.
  
  - Hablar un poco de algunas de las ideas del Tema 1
  
  - ¿Cómo trabajaremos con R? Workflow
  
  - Ejemplos iniciales
  

<br>


##### Cosas que has de (medio) entender/saber hacer después de la clase

Muchas veces para (medio) entender/saber hacer estas cosas tendrás que asistir a tutorías o estudiar o preguntar a un compañero, o .... 

  - ¿Qué es la ciencia de datos?
  
  - ¿Qué es R y RStudio? ¿Y los paquetes?

  - ¿Qué son los ficheros .R? ¿Y los .Rmd? ¿Y los Rprojects?
   
  - Saber interactuar con R a través de Rprojects
   

<br>

Too much for the first class? Igual sí. Al final veremos lo que podamos. Primero tenemos que adaptarnos a las condiciones .

-----------------------

<br>

## 2ª clase (25-sept)

##### **`Homework`** (para hacer antes de ir a clase) 

- Leer el e-mail que os he mandado a vuestro correo de la UV y hacer (si quieres) las 3 tareas extra-oficiales que allí os cuento. Además, en el mail hay una cuarta tarea, está cuarta tarea sí es oficial, hay que hacerla.

- Leer el [tutorial nº 2](https://perezp44.github.io/intro-ds-20-21-web/tutoriales/tt_02_primeros-pasos-con-R.html). En el tutorial aparece una pequeña explicación de las ventajas de usar Rprojects y hace hincapié en el concepto de **rutas relativas**. Trata de entenderlo, lógicamente, pero si tienes dudas/problemas no pasa nada, lo trabajaremos en profundidad cuando empecemos el tutorial nº 04, supongo que en la tercera sesión/viernes del curso.

- Configurar RStudio. Para ello tienes que seguir las instrucciones que figuran en el tutorial nº 2, concretamente [aquí](https://perezp44.github.io/intro-ds-20-21-web/tutoriales/tt_02_primeros-pasos-con-R.html#Configurando_RStudio). Es importante que tengamos todos la misma configuración, ya explicaré la razón en clase.



##### ¿Qué haremos en la segunda clase?

  - Finalizar las [Slides-03: Primeros pasos](./slides/ss_03_inicio-curso/ss_03_primeros-pasos.html){target="_blank"}. para tratar de acabar de entender/habituarnos a RStudio, los Rprojects etc ...
  
- Estaremos un buen rato con el ejemplo "ej_01_ejemplo-inicial.R"; es un análisis muy simple, pero ejemplifica bien lo que haremos durante el curso.
  
- Utilizaremos el fichero "ej_01_ejemplo-inicial.Rmd" para crear una primera capa para entender los ficheros .Rmd
  
- Ver todo los que podamos de R-base, para ello utilizaremos las [Slides-04: R base](./slides/ss_04_R-base-01/ss_04_R-base-01.html){target="_blank"}. Es muy importante entender algunos conceptos como asignación, tipos de datos, estructuras de datos, funciones ...


<br>

-----------------------

<br>

## 3ª clase (2-oct)


##### **`Homework`** (para hacer antes de ir a clase) 

- Leer el e-mail que os he mandado a vuestro correo de la UV. Allí están los detalles de la primera entrega que **forma parte de la evaluación continua**. Hay que entregarla antes del jueves 1 de octubre a las 23:59.

- La principal tarea que tenéis que hacer está semana es repasar un poco lo que hemos visto y ver si te vas sintiendo cómodo en R/RStudio. 

-  Volver a leer el primer apartado del [`Tutorial 03: R base`](./tutoriales/tt_03_R-base.html){target="_blank"}

- Leer e intentar ejecutar el código de las [Slides-04: R base](./slides/ss_04_R-base-01/ss_04_R-base-01.html){target="_blank"}. 

- Leer e intentar ejecutar el código de las [Slides-05: Importar y exportar datos](./slides/ss_05_cargar-datos/ss_05_cargar-datos.html){target="_blank"}. Mejor si llegas al final, pero hasta donde llegues.


##### ¿Qué haremos en la tercera clase?

- "Corregir" la primera entrega.

- Hablar de la evaluación

- Acabar con el "tema" de R-base. Para ello utilizaremos las [Slides-04: R base](./slides/ss_04_R-base-01/ss_04_R-base-01.html){target="_blank"}.

- Empezar a importar/exportar datos. Para ello usaremos las [Slides-05: Importar y exportar datos](./slides/ss_05_cargar-datos/ss_05_cargar-datos.html){target="_blank"}.
  
  
  
 
<br>

-----------------------

<br>

## 4ª clase (16-oct)


##### **`Homework`** (para hacer antes de ir a clase) 

- Leer el e-mail que os he mandado a vuestro correo de la UV. Esta vez no hay entrega pero os hablo de varios asuntos.

- Otra vez, la principal tarea que tenéis que hacer es repasar lo que hemos visto.

- Leer e intentar ejecutar el código de las [Slides-05: Importar y exportar datos](./slides/ss_05_cargar-datos/ss_05_cargar-datos.html){target="_blank"}. 

- Leer todo lo que puedas del [`Tutorial 05: Data munging`](./tutoriales/tt_05_data-munging.html){target="_blank"}. El tutorial 04 no es importante que lo leas, pero sí el tutorial 05.

- Por favor, aquellos que no tengan bien configurado RStudio que lo hagan esta semana. Para ello tienes que seguir las instrucciones que figuran en el tutorial nº 2, concretamente [aquí](https://perezp44.github.io/intro-ds-20-21-web/tutoriales/tt_02_primeros-pasos-con-R.html#Configurando_RStudio).



##### ¿Qué haremos en la cuarta clase?

- Hablar sobre los 2 proyectos que forman parte de la evaluación continua, principalmente del trabajo en equipo.

- Empezar por fin con el `tidyverse`:

    - Aprenderemos a importar y exportar datos. para ello usaremos las [Slides-05: Importar y exportar datos](./slides/ss_05_cargar-datos/ss_05_cargar-datos.html){target="_blank"}. 
  

    - Empezar a manipular datos à la tidyverse. Presentaremos ideas/conceptos como "the pipe" y "tidy data" y empezaremos a usar 2 paquetes del tidyverse: `tidyr` y `dplyr`, el principal paquete para manipular datos. Para ello usaremos las [Slides-05(bis): Data munging](./slides/ss_05_data-munging/ss_05_data-munging.html){target="_blank"}.
  
  
  

<br>

-----------------------

<br>

## 5ª clase (23-oct)


##### **`Homework`** (para hacer antes de ir a clase) 

- Leer el e-mail que os he mandado a vuestro correo de la UV. Esta vez sí hay entrega, la tercera. Ayer hicimos la segunda en clase.

- Lee todo lo que puedas del [`Tutorial 05: Data munging`](./tutoriales/tt_05_data-munging.html){target="_blank"}. 

- Leer e intentar ejecutar el código de las [Slides-05(bis): Data munging](./slides/ss_05_data-munging/ss_05_data-munging.html){target="_blank"}.


##### ¿Qué haremos en clase?

- "Corregir" ... bueno en realidad ver algunos de los fallos que tuvisteis en la entrega_02. Se trata de no repetir errores y aprender de ellos.

- Meternos de lleno con el `tidyverse`, concretamente con su principal paquete `dplyr`. Necesito que os leáis el tutorial 05 y las slides 05, please!!!!!

- Espero, no sé si lo conseguiremos, pero espero empezar a hablar de ggplot2 y hacer nuestro primer super-gráfico.
  



  
  <br><br><br><br>
