---
#title: "Macroenometrics (44343)"
output:
  html_document:
    css: assets/styles_pjp.css
    theme: united
    highlight: monochrome 
    number_sections: no
    toc: true
    toc_float: true
---


```{r, echo = FALSE}
library(metathis)
meta() %>% meta_description(
    "Curso de introduccion a R"
  ) %>% 
  meta_name("github-repo" = "perezp44/intro-ds-20-21-web") %>% 
  meta_viewport() %>% 
  meta_social(
    title = "Curso de introducción a R",
    url = "https://perezp44.github.io/intro-ds-20-21-web/",
    og_type = "course",
    og_author = c("Pedro J. Pérez"))
```



```{r klippy, echo = FALSE}
klippy::klippy(position = c("top", "right")) #- remotes::install_github("rlesur/klippy")
```


<br>

### Trabajos estudiantes

-------------------

Los estudiantes del curso, como parte de la evaluación continua, tuvieron que presentar dos trabajos, uno individual y otro en equipo. Puedes verlos en los siguientes enlaces:


-----------------------------------

<br>

#### Trabajos en equipo

<br>

----------------------------------

<br>

#### Trabajos individuales

<br>

- **Pedro Jose Pérez Vázquez** presentó el trabajo [la docencia de R en la UV](https://perezp44.github.io/trabajo_BigData/){target="_blank"}. El repo está [aquí](https://github.com/perezp44/trabajo_BigData){target="_blank"}.

<br><br>
