#- paquetes de R a instalar ----------------------------
install.packages("remotes") #- este paquete se necesita para instalar otros, asi que instalar en primer lugar
install.packages(c("ggthemes", "jtools", "tidyverse"))
install.packages(c("rprojroot", "huxtable"))
install.packages("ggpol")
install.packages("eurostat")
install.packages(c("corrplot", "essurvey", "rio", "sjlabelled", "sjPlot", "skimr", "summarytools", "visdat"))
remotes::install_github("perezp44/pjpv2020.01")
install.packages(c("cowplot", "tabulizer"))
remotes::install_github("xvrdm/ggrough")
install.packages("htmlwidgets")
install.packages("rtweet")
install.packages("gganimate")
install.packages("SPARQL")
install.packages("devtools")
devtools::install_github("hmeleiro/elecciones")
install.packages("meme")
install.packages(c("plotly", "spotifyr", "tidytext", "tm", "wordcloud2"))
install.packages(c("leaflet", "tmap"))
install.packages("pxR")
install.packages("ggridges")
install.packages("OECD")
install.packages("datasauRus")
install.packages("gapminder")
install.packages("gifski")
install.packages("flextable")
install.packages("fs")
install.packages("here")
install.packages("tidyquant")
install.packages("quantmod")
install.packages("knitr")
install.packages("patchwork")
install.packages("gridExtra")
install.packages("viridis")
devtools::install_github("LKremer/ggpointdensity")
install.packages("ggrepel")
install.packages("janitor")
install.packages("GGally")
install.packages("ggThemeAssist")
install.packages("scales")
install.packages("ggforce")
install.packages("gghighlight")
install.packages("esquisse")
install.packages("flexdashboard")
install.packages("rmdformats")
install.packages("vitae")
install.packages("learnr")
install.packages("scholar")
install.packages("tinytex")
install.packages("pagedown")
remotes::install_github("rstudio/gt")
install.packages(c("apaTables", "formattable", "kableExtra", "modelsummary", "rpivotTable", "stargazer", "xlsx"))
devtools::install_github("strengejacke/strengejacke")
install.packages(c("corrr", "DataExplorer", "estimatr", "explore", "factoextra", "FactoMineR", "funModeling", "ggfortify", "ggparty", "inspectdf", "lmtest", "margins", "naniar", "NHANES", "psycho", "rattle"))
remotes::install_github("datalorax/equatiomatic")
install.packages("psycho")
install.packages("reportr")
install.packages(c("ggspatial", "rnaturalearth", "rnaturalearthdata"))
install.packages(c("leafem", "leafpm", "mapedit", "mapview"))
install.packages("rworldmap")
install.packages("stationaRy")
remotes::install_github("adam-gruer/victor")
install.packages(c("ggmap", "osmdata"))
install.packages("reactable")
remotes::install_github("juba/rmdformats")
install.packages("googlePolylines")
install.packages("geojsonsf")
install.packages("geojsonlint")
remotes::install_github("GIScience/openrouteservice-r")
remotes::install_github("perezp44/LAU2boundaries4spain")
install.packages(c( "lattice", "grid", "graphics", "carData","gridGraphics", "timetk", "fmsb", "vcd","ggmosaic", "wordcloud","maptools", "RColorBrewer", "cartogram", "igraph", "ggraph"))
install.packages("actuar")
install.packages("ChainLadder", "VGAM", "compoisson", "pscl")

